// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAuthRole = "auth_role"

// AuthRole mapped from table <auth_role>
type AuthRole struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Fname     string         `gorm:"column:fname;not null" json:"fname"`
	Fnote     string         `gorm:"column:fnote" json:"fnote"`
}

// TableName AuthRole's table name
func (*AuthRole) TableName() string {
	return TableNameAuthRole
}
