// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAuthUser = "auth_user"

// AuthUser mapped from table <auth_user>
type AuthUser struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Username  string         `gorm:"column:username;not null" json:"username"`
	Password  string         `gorm:"column:password;not null" json:"password"`
	Nickname  string         `gorm:"column:nickname;not null" json:"nickname"`
	Ftype     int64          `gorm:"column:ftype" json:"ftype"`
	Fnote     string         `gorm:"column:fnote" json:"fnote"`
}

// TableName AuthUser's table name
func (*AuthUser) TableName() string {
	return TableNameAuthUser
}
