// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAuthUserRole = "auth_user_role"

// AuthUserRole mapped from table <auth_user_role>
type AuthUserRole struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserID    int64          `gorm:"column:userID;not null" json:"userID"`
	RoleID    int64          `gorm:"column:roleID;not null" json:"roleID"`
}

// TableName AuthUserRole's table name
func (*AuthUserRole) TableName() string {
	return TableNameAuthUserRole
}
