// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAuthMenu = "auth_menu"

// AuthMenu mapped from table <auth_menu>
type AuthMenu struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name         string         `gorm:"column:name" json:"name"`
	ParentID     int64          `gorm:"column:parentId" json:"parentId"`
	URL          string         `gorm:"column:url" json:"url"`
	Perms        string         `gorm:"column:perms" json:"perms"`
	Icon         string         `gorm:"column:icon" json:"icon"`
	OrderNum     int64          `gorm:"column:orderNum" json:"orderNum"`
	VuePath      string         `gorm:"column:vuePath" json:"vuePath"`
	VueComponent string         `gorm:"column:vueComponent" json:"vueComponent"`
	VueRedirect  string         `gorm:"column:vueRedirect" json:"vueRedirect"`
	Ftype        int64          `gorm:"column:ftype" json:"ftype"`
}

// TableName AuthMenu's table name
func (*AuthMenu) TableName() string {
	return TableNameAuthMenu
}
