// Code generated by goctl. DO NOT EDIT.
package types

type AddAuthUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Ftype    int    `json:"ftype,default=0"`
	Fnote    string `json:"fnote,optional"`
}

type FindAuthUserReq struct {
	Username string `json:"username,optional"`
	Nickname string `json:"nickname,optional"`
	Ftype    int64  `json:"ftype,optional"`
}

type FindAuthUserResp struct {
	Id             int64       `json:"id"`
	Username       string      `json:"username"`
	Nickname       string      `json:"nickname"`
	Ftype          int64       `json:"ftype"`
	Fnote          string      `json:"fnote"`
	CreateDatetime string      `json:"createDatetime"`
	Roles          interface{} `json:"roles"`
}

type UpdateAuthUserReq struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Ftype    int64  `json:"ftype,default=0"`
	Fnote    string `json:"fnote,optional"`
}

type DeleteAuthUserReq struct {
	Id []int64 `json:"id"`
}

type ResultResponse struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type AddAuthRoleReq struct {
	Fname string `json:"fname"`
	Fnote string `json:"fnote"`
}

type FindAuthRoleReq struct {
	Fname string `json:"fname,optional"`
}

type FindAuthRoleResp struct {
	Id             int64       `json:"id"`
	Fname          string      `json:"fname"`
	Fnote          string      `json:"fnote"`
	CreateDatetime string      `json:"createDatetime"`
	Users          interface{} `json:"users"`
}

type UpdateAuthRoleReq struct {
	Id    int64  `json:"id"`
	Fname string `json:"fname"`
	Fnote string `json:"fnote,optional"`
}

type DeleteAuthRoleReq struct {
	Id []int64 `json:"id"`
}

type AddUserRole struct {
	UserId int64 `json:"userId"`
	RoleId int64 `json:"roleId"`
}

type UserRoleReq struct {
	UserRoleLst []AddUserRole `json:"userRoleLst"`
}
